# Generated by Django 2.1.1 on 2018-09-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_descrip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descrip',
            new_name='description',
        ),
    ]
